return {
    { image = 'iconPerks_agitation',                    lang = { 'Agitation', '興奮', 'Erregung' } },
    { image = 'iconPerks_aNursesCalling',               lang = { 'A Nurse\'s Calling', '看護婦の使命', 'Der Ruf einer Krankenschwester' } },
    { image = 'iconPerks_bitterMurmur',                 lang = { 'Bitter Murmur', '憎悪の囁き', 'Verbittertes Gemurmel' } },
    { image = 'iconPerks_bloodhound',                   lang = { 'Bloodhound', '血の追跡者', 'Bluthund' } },
    { image = 'iconPerks_brutalStrength',               lang = { 'Brutal Strength', '野蛮な力', 'Brutale Stärke' } },

    { image = 'iconPerks_deerstalker',                  lang = { 'Deerstalker', '忍び寄る者', 'Pirscher' } },
    { image = 'iconPerks_distressing',                  lang = { 'Distressing', '苦悶の根源', 'Verstört' } },
    { image = 'iconPerks_enduring',                     lang = { 'Enduring', '不屈', 'Beständig' } },
    { image = 'iconPerks_insidious',                    lang = { 'Insidious', '狡猾', 'Heimtückisch' } },
    { image = 'iconPerks_ironGrasp',                    lang = { 'Iron Grasp', '鋼の握力', 'Eiserner Griff' } },
-- 10
    { image = 'iconPerks_lightborn',                    lang = { 'Lightborn', '光より出でし者', 'Lichtgeborener' } },
    { image = 'iconPerks_monstrousShrine',              lang = { 'Monstrous Shrine', '異形の祭壇', 'Monströser Schrein' } },
    { image = 'iconPerks_noOneEscapesDeath',            lang = { 'Hex: No One Escapes the Death', '呪術・誰も死から逃れられない', 'Fluch: Niemand entrinnt dem Tod' } },
    { image = 'iconPerks_predator',                     lang = { 'Predator', '捕食者', 'Räuber' } },
    { image = 'iconPerks_shadowborn',                   lang = { 'Shadowborn', '闇より出でし者', 'Schattengeborener' } },

    { image = 'iconPerks_sloppyButcher',                lang = { 'Sloppy Butcher', 'ずさんな肉屋', 'Schlampiger Schlachter' } },
    { image = 'iconPerks_spiesFromTheShadows',          lang = { 'Spies from the Shadows', '影の密偵', 'Spione des Schattens' } },
    { image = 'iconPerks_stridor',                      lang = { 'Stridor', '喘鳴', 'Stridor' } },
    { image = 'iconPerks_thatanophobia',                lang = { 'Thatanophobia', '死恐怖症', 'Thanatophobia' } },
    { image = 'iconPerks_tinkerer',                     lang = { 'Tinkerer', 'ガラクタいじり', 'Tüftler' } },
-- 20
    { image = 'iconPerks_unnervingPresence',            lang = { 'Unnerving Presence', '不安の元凶', 'Zermürbende Präsenz' } },
    { image = 'iconPerks_unrelenting',                  lang = { 'Unrelenting', '無慈悲', 'Unerbittlich' } },
    { image = 'iconPerks_whispers',                     lang = { 'Whispers', '囁き', 'GeflüsterGrausame Grenzen' } },
    { image = 'Cannibal/iconPerks_BBQAndChili',         lang = { 'Barbecue & Chili', 'バーベキュー＆チリ', 'Barbecue und Chili' } },
    { image = 'Wales/iconPerks_trailOfTorment',         lang = { 'Trail of Torment', '煩悶のトレイル', 'Pfad der Folter' } },

    { image = 'Cannibal/iconPerks_franklinsLoss',       lang = { 'Franklin\'s Demise', 'フランクリンの悲劇', 'Franklins Niedergang' } },
    { image = 'Cannibal/iconPerks_knockOut',            lang = { 'Knock Out', 'ノックアウト', 'K.O.' } },
    { image = 'DLC2/iconPerks_dyingLight',              lang = { 'Dying Light', '消えゆく灯', 'Erlischendes Licht' } },
    { image = 'DLC2/iconPerks_playWithYourFood',        lang = { 'Play with your Food', '弄ばれる獲物', 'Spiele mit deinem Essen' } },
    { image = 'DLC2/iconPerks_saveTheBestForLast',      lang = { 'Save the best for Last', '最後のお楽しみ', 'Das Beste kommt zum Schluss' } },
-- 30
    { image = 'DLC3/iconPerks_devourHope',              lang = { 'Hex: Devour Hope', '呪術・貪られる希望', 'Fluch: Aufgezehrte Hoffnung' } },
    { image = 'DLC3/iconPerks_ruin',                    lang = { 'Hex: Ruin', '呪術・破滅', 'Fluch: Ruin' } },
    { image = 'DLC3/iconPerks_theThirdSeal',            lang = { 'Hex: The third Seal', '呪術・第三の封印', 'Fluch: Das dritte Siegel' } },
    { image = 'DLC3/iconPerks_thrillOfTheHunt',         lang = { 'Hex: Thrill of the Hunt', '呪術・狩りの興奮', 'Fluch: Nervenkitzel der Jagd' } },
    { image = 'DLC4/iconPerks_generatorOvercharge',     lang = { 'Generator Overcharge', 'オーバーチャージ', 'Überladen' } },

    { image = 'DLC4/iconPerks_monitorAndAbuse',         lang = { 'Monitor and Abuse', '観察＆虐待', 'Beobachten und Zuschlagen' } },
    { image = 'DLC4/iconPerks_overwhelmingPresence',    lang = { 'Overhelming Presence', '圧倒的存在感', 'Erdrückende Präsenz' } },
    { image = 'DLC5/iconPerks_BeastOfPrey',             lang = { 'Beast of Prey', '猛獣', 'Raubtier' } },
    { image = 'DLC5/iconPerks_HuntressLullaby',         lang = { 'Hex: Huntress Lullaby', '呪術・女狩人の子守歌', 'Fluch: Wiegenlied der Jägerin' } },
    { image = 'DLC5/iconPerks_TerritorialImperative',   lang = { 'Territorial Imperative', '縄張り意識', 'Gebietszwang' } },
-- 40
    { image = 'England/iconPerks_bloodWarden',          lang = { 'Blood Warden', '血の番人', 'Blutwächter' } },
    { image = 'England/iconPerks_fireUp',               lang = { 'Fire Up', 'ファイヤー・アップ', 'Einheizen' } },
    { image = 'England/iconPerks_rememberMe',           lang = { 'Rember Me', 'リメンバー・ミー', 'Vergissmeinnicht' } },
    { image = 'Finland/iconPerks_hangmansTrick',        lang = { 'Hangman\'s Trick', '処刑人の妙技', 'Henkerstreich' } },
    { image = 'Finland/iconPerks_makeYourChoice',       lang = { 'Make your Choice', '選択は君次第だ', 'Triff deine Wahl' } },

    { image = 'Finland/iconPerks_surveillance',         lang = { 'Surveillance', '監視', 'Überwachung' } },
    { image = 'Guam/iconPerks_bamboozle',               lang = { 'Bamboozle', 'まやかし', 'Verblüffen' } },
    { image = 'Guam/iconPerks_coulrophobia',            lang = { 'Coulrophobia', 'ピエロ恐怖症', 'Coulrophobie' } },
    { image = 'Guam/iconPerks_popGoesTheWeasel',        lang = { 'Pop goes the Weasel', 'イタチが飛び出した', 'Pop Goes the Weasel' } },
    { image = 'Haiti/iconPerks_hatred',                 lang = { 'Rancor', '怨恨', 'Hass' } },
-- 50
    { image = 'Haiti/iconPerks_hauntedGround',          lang = { 'Hex: Haunted Ground', '呪術・霊障の地', 'Fluch: Heimgesuchter Boden' } },
    { image = 'Haiti/iconPerks_spiritFury',             lang = { 'Spirit Fury', '怨霊の怒り', 'Zorn des Gespensts' } },
    { image = 'Kenya/iconPerks_discordance',            lang = { 'Discordance', '不協和音', 'Uneinigkeit' } },
    { image = 'Kenya/iconPerks_ironMaiden',             lang = { 'Iron Maiden', 'アイアンメイデン', 'Eiserne Jungfrau' } },
    { image = 'Kenya/iconPerks_madGrit',                lang = { 'Mad Grit', '狂気の根性', 'Irrer Mut' } },

    { image = 'Mali/iconPerks_corruptIntervention',     lang = { 'Corrupt Intervention', '堕落の介入', 'Korrupte Intervention' } },
    { image = 'Mali/iconPerks_darkDevotion',            lang = { 'Dark Devotion', '闇の信仰心', 'Dunkle Hingabe' } },
    { image = 'Mali/iconPerks_infectiousFright',        lang = { 'Infectious Fright', '伝播する怖気', 'Infektiöse Angst' } },
    { image = 'Oman/iconPerks_furtiveChase',            lang = { 'Furtive Chase', '隠密の追跡', 'Heimliche Verfolgungsjagd' } },
    { image = 'Oman/iconPerks_imAllEars',               lang = { 'I\'m all Ears', '地獄耳', 'Ich bin ganz Ohr' } },
-- 60
    { image = 'Oman/iconPerks_thrillingTremors',        lang = { 'Thrilling Tremors', '戦慄', 'Durchdringendes Zittern' } },
    { image = 'Qatar/iconPerks_cruelConfinement',       lang = { 'Cruel Confinement', '無慈悲の極地', 'Grausame Grenzen' } },
    { image = 'Qatar/iconPerks_mindBreaker',            lang = { 'Mind Breaker', 'マインドブレーカー', 'Seelenbrecher' } },
    { image = 'Qatar/iconPerks_surge',                  lang = { 'Surge', 'サージ', 'Spannungsstoß' } },
    { image = 'Sweden/iconPerks_bloodEcho',             lang = { 'Blood Echo', '血の共鳴', 'Blutecho' } },

    { image = 'Sweden/iconPerks_nemesis',               lang = { 'Nemesis', '天誅', 'Nemesis' } },
    { image = 'Sweden/iconPerks_zanshinTactics',        lang = { 'Zanshin Tactics', '残心の戦術', 'Zanshin-Taktik' } },
    { image = 'Ukraine/iconPerks_deadManSwitch',        lang = { 'Dead Man Switch', '死人のスイッチ', 'Totenschalter' } },
    { image = 'Ukraine/iconPerks_gearHead',             lang = { 'Gear Head', '変速機', 'Ausrüstungsspezi' } },
    { image = 'Ukraine/iconPerks_hexRetribution',       lang = { 'Hex: Retribution', '呪術：報復', 'Fluch: Vergeltung' } },
-- 70
    { image = 'Wales/iconPerks_deathbound',             lang = { 'Deathound', 'デスバウンド', 'Todgeweiht' } },
    { image = 'Wales/iconPerks_forcedPenance',          lang = { 'Forced Penance', '強制苦行', 'Erzwungene Buße' } },
    { image = 'Yemen/iconPerks_dragonsGrip',            lang = { 'Dragon Grip', 'ドラゴンの掌握', 'Drachengriff' } },
    { image = 'Yemen/iconPerks_hexBloodFavor',          lang = { 'Hex: Blood Favor', '呪術：血の恩恵',  'Fluch: Blutgunst' } },
    { image = 'Yemen/iconPerks_hexUndying',             lang = { 'Hex: Undying', '呪術：不死', 'Fluch: Unsterblich' } }, 
    
    { image = 'Aurora/iconPerks_Hoarder',               lang = {'Hoarder', 'ひきこもり', 'Horter'} },
    { image = 'Aurora/iconPerks_Oppression',            lang = {'Oppression', '抑圧', 'Unterdrückung'} },
    { image = 'Aurora/iconPerks_coupDeGrace',           lang = {'Coup de Grâce', '恩寵の一撃', 'Gnadenstoß'} },
}
