return {
    { image = 'iconPerks_adrenaline',                   lang = { 'Adrenaline', 'アドレナリン', 'Adrenalin' } },
    { image = 'iconPerks_balancedLanding',              lang = { 'Balance Landing', 'スマートな着地', 'Ausgewogene Landung' } },
    { image = 'iconPerks_bond',                         lang = { 'Bond', '絆', 'Bindung' } },
    { image = 'iconPerks_botanyKnowledge',              lang = { 'Botany Knowledge', '植物学の知識', 'Botanisches Wissen' } },
    { image = 'iconPerks_calmSpirit',                   lang = { 'Calm Spirit', '魂の平穏', 'Seelenruhe' } },

    { image = 'iconPerks_darkSense',                    lang = { 'Dark Sense', '闇の感覚', 'Dunkle Wahrnehmung' } },
    { image = 'iconPerks_dejaVu',                       lang = { 'Déjà-Vu', 'デジャヴ', 'Déjà-Vu-Erlebnis' } },
    { image = 'iconPerks_empathy',                      lang = { 'Empathy', '共感', 'Einfühlungsvermögen' } },
    { image = 'iconPerks_hope',                         lang = { 'Hope', '希望', 'Hoffnung' } },
    { image = 'iconPerks_ironWill',                     lang = { 'Iron Will', '鋼の意思', 'Eiserner Wille' } },
-- 10
    { image = 'iconPerks_kindred',                      lang = { 'Kindred', '血族', 'Verwandt' } },
    { image = 'iconPerks_leader',                       lang = { 'Leader', 'リーダー', 'Anführer' } },
    { image = 'iconPerks_lightweight',                  lang = { 'Lightweight', '身軽', 'Leichtgewicht' } },
    { image = 'iconPerks_noOneLeftBehind',              lang = { 'No One Left Behind', '誰も見捨てはしない', 'Niemand wird Zurückgelassen' } },
    { image = 'iconPerks_plunderersInstinct',           lang = { 'Plunderers Instinct', 'コソ泥の本能', 'Plündererspürsinn' } },

    { image = 'iconPerks_premonition',                  lang = { 'Premonition', '予感', 'Vorwarnung' } },
    { image = 'iconPerks_proveThyself',                 lang = { 'Prove Thyself', '有能の証明', 'Beweise dich' } },
    { image = 'iconPerks_quickAndQuiet',                lang = { 'Quick & Quiet', '素早く静かに', 'Schnell & Leise' } },
    { image = 'iconPerks_resilience',                   lang = { 'Resilience', '逆境魂', 'Widerstandsfähigkeit' } },
    { image = 'iconPerks_saboteur',                     lang = { 'Saboteur', 'サボタージュ', 'Saboteur' } },
-- 20
    { image = 'iconPerks_selfCare',                     lang = { 'Self Care', 'セルフケア', 'Selbstfürsorge' } },
    { image = 'iconPerks_slipperyMeat',                 lang = { 'Slippery Meat', 'ツルツルとした肉体', 'Gerissenes Fleisch' } },
    { image = 'iconPerks_smallGame',                    lang = { 'Small Game', '小さな獲物', 'Niederwild' } },
    { image = 'iconPerks_spineChill',                   lang = { 'Spine Chill', '凍りつく背筋', 'Kalter Rückenschauer' } },
    { image = 'iconPerks_sprintBurst',                  lang = { 'Sprint Burst', '全力疾走', 'Sprintboost' } },

    { image = 'iconPerks_streetwise',                   lang = { 'Streetwise', '都会の生存術', 'Pfiffig' } },
    { image = 'iconPerks_thisIsNotHappening',           lang = { 'This is not happening', '痛みも気から', 'Das geschieht nicht' } },
    { image = 'iconPerks_urbanEvasion',                 lang = { 'Urban Evasion', '都会の逃走術', 'Städtische Invasion' } },
    { image = 'iconPerks_wellMakeIt',                   lang = { 'We\'ll make it', 'きっとやり遂げる', 'Wir schaffen das!' } },
    { image = 'Ash/iconPerks_buckleUp',                 lang = { 'Buckle Up', 'ベルトを締めろ！', 'Anschnallen' } },
-- 30
    { image = 'Ash/iconPerks_flipFlop',                 lang = { 'Flip Flop', 'フリップ・フロップ', 'Flip-Flop' } },
    { image = 'Ash/iconPerks_mettleOfMan',              lang = { 'Mettle of Man', '英雄の奮起', 'Der Eifer der Menschen' } },
    { image = 'DLC2/iconPerks_decisiveStrike',          lang = { 'Decisive Strike', '決死の一撃', 'Entscheidungsschlag' } },
    { image = 'DLC2/iconPerks_objectOfObsession',       lang = { 'Object of Obsession', '執念の対象', 'Objekt der Besessenheit' } },
    { image = 'DLC2/iconPerks_soleSurvivor',            lang = { 'Sole Survivor', '唯一の生存者', 'Einziger Überlebender' } },

    { image = 'DLC3/iconPerks_aceInTheHole',            lang = { 'Ace in the Hole', '最後の切り札', 'Ass im Ärmel' } },
    { image = 'DLC3/iconPerks_openHanded',              lang = { 'Open Handed', '手札公開', 'Mit offener Hand' } },
    { image = 'DLC3/iconPerks_upTheAnte',               lang = { 'Up the Ante', '賭け金のレイズ', 'Erhöhe den Einsatz' } },
    { image = 'DLC4/iconPerks_alert',                   lang = { 'Alert', '警戒', 'Wachsam' } },
    { image = 'DLC4/iconPerks_lithe',                   lang = { 'Lithe', 'しなやか', 'Flink' } },
-- 40
    { image = 'DLC4/iconPerks_technician',              lang = { 'Technician', 'テクニシャン', 'Technikerin' } },
    { image = 'DLC5/iconPerks_DeadHard',                lang = { 'Dead Hard', 'デッド・ハード', 'Hart im Nehmen' } },
    { image = 'DLC5/iconPerks_NoMither',                lang = { 'No Mither', '弱音はナシだ', 'Kein Gejammer' } },
    { image = 'DLC5/iconPerks_WereGonnaLiveForever',    lang = { 'We\'re gonna Live forever', 'ずっと一緒だ', 'Wir werden ewig Leben' } },
    { image = 'England/iconPerks_pharmacy',             lang = { 'Pharmacy', '調剤学', 'Apotheke' } },

    { image = 'England/iconPerks_vigil',                lang = { 'Vigil', '寝ずの番', 'Nachtwache' } },
    { image = 'England/iconPerks_wakeUp',               lang = { 'Wake up!', '目を覚ませ！', 'Aufwachen!' } },
    { image = 'Finland/iconPerks_detectivesHunch',      lang = { 'Detectives Hunch', '張り込み', 'Tapps Verdacht' } },
    { image = 'Finland/iconPerks_stakeOut',             lang = { 'Stake Out', '刑事の直感', 'Observierung' } },
    { image = 'Finland/iconPerks_tenacity',             lang = { 'Tenacity', '執念', 'Beharrlichkeit' } },
-- 50
    { image = 'Haiti/iconPerks_autodidact',             lang = { 'Autodidact', '独学者', 'Autodidakt' } },
    { image = 'Haiti/iconPerks_deliverance',            lang = { 'Deliverence', '解放', 'Befreiung' } },
    { image = 'Haiti/iconPerks_diversion',              lang = { 'Diversion', '陽動', 'Ablenkung' } },
    { image = 'Kate/iconPerks_boilOver',                lang = { 'Boil Over', 'ボイルオーバー', 'Wildpferd' } },
    { image = 'Kate/iconPerks_danceWithMe',             lang = { 'Dance with me', 'ダンス・ウィズ・ミー', 'Tanz mit mir' } },

    { image = 'Kate/iconPerks_windowsOfOpportunity',    lang = { 'Windows of Opportunity', 'ウィンドウズ・オブ・オポチュニティ', 'Gelegenheit nutzen' } },
    { image = 'Kenya/iconPerks_aftercare',              lang = { 'Aftercare', 'アフターケア', 'Nachsorge' } },
    { image = 'Kenya/iconPerks_breakdown',              lang = { 'Breakdown', 'ブレイクダウン', 'Zerlegen' } },
    { image = 'Kenya/iconPerks_distortion',             lang = { 'Distortion', 'ディストーション', 'Verzerrung' } },
    { image = 'L4D/iconPerks_borrowedTime',             lang = { 'Borrowed Time', '与えられた猶予', 'Geliehene Zeit' } },
-- 60
    { image = 'L4D/iconPerks_leftBehind',               lang = { 'Left Behind', '置き去りにされた者', 'Zurückgelassen' } },
    { image = 'L4D/iconPerks_unbreakable',              lang = { 'Unbreakable', '不滅', 'Unbeugsam' } },
    { image = 'Mali/iconPerks_headOn',                  lang = { 'Head On', '真っ向勝負', 'Frontal' } },
    { image = 'Mali/iconPerks_poised',                  lang = { 'Poised', '平常心', 'Selbstsicher' } },
    { image = 'Mali/iconPerks_solidarity',              lang = { 'Solidarity', '連帯感', 'Solidarität' } },

    { image = 'Qatar/iconPerks_babySitter',             lang = { 'Baby Sitter', 'ベビーシッター', 'Babysitter' } },
    { image = 'Qatar/iconPerks_betterTogether',         lang = { 'Better Together', '一緒にいよう', 'Besser Gemeinsam' } },
    { image = 'Qatar/iconPerks_fixated',                lang = { 'Fixated', '執着心', 'Fixiert' } },
    { image = 'Qatar/iconPerks_innerStrength',          lang = { 'Inner Strength', '内なる力', 'Innere Kraft' } },
    { image = 'Qatar/iconPerks_secondWind',             lang = { 'Second Wind', 'セカンドウインド', 'Aufschwung' } },
-- 70
    { image = 'Qatar/iconPerks_camaraderie',            lang = { 'Camaraderie', '仲間意識', 'Kameradschaft' } },
    { image = 'Sweden/iconPerks_anyMeansNecessary',     lang = { 'Any means Necessary', '強硬手段', 'Mit allen Mitteln' } },
    { image = 'Sweden/iconPerks_breakout',              lang = { 'Breakout', '突破', 'Ausbruch' } },
    { image = 'Sweden/iconPerks_luckyBreak',            lang = { 'Lucky Break', '怪我の功名', 'Glück gehabt' } },
    { image = 'Ukraine/iconPerks_forThePeople',         lang = { 'For the People', '人々のために', 'Für das Volk' } },

    { image = 'Ukraine/iconPerks_offTheRecord',         lang = { 'Off the Record', 'オフレコ', 'Vertraulich' } },
    { image = 'Ukraine/iconPerks_redHerring',           lang = { 'Red Herring', 'おとり', 'Ablenkungsmanöver' } },
    { image = 'Wales/iconPerks_bloodPact',              lang = { 'Blood Pact', '血の協定', 'Blutpakt' } },
    { image = 'Wales/iconPerks_repressedAlliance',      lang = { 'Repressed Alliance', '抑圧の同盟', 'Verdrängtes Bündnis' } },
    { image = 'Wales/iconPerks_soulGuard',              lang = { 'Soul Guard', 'ソウルガード', 'Seelenwächter' } },
-- 80
    { image = 'Yemen/iconPerks_builtToLast',            lang = { 'Built to Last', '耐久設計', 'Gebaut für die Ewigkeit' } },
    { image = 'Yemen/iconPerks_desperateMeasures',      lang = { 'Desperate Measures', '苦肉の策', 'Verzweifelte Maßnahmen' } },
    { image = 'Yemen/iconPerks_visionary',              lang = { 'Visionary', '透視家', 'Visionär' } },
    { image = 'Aurora/iconPerks_appraisal',             lang = {'Appraisal', '鑑定評価', 'Einschätzung'} },
    { image = 'Aurora/iconPerks_deception',             lang = {'Deception', '欺瞞', 'Täuschung'} },
    
    { image = 'Aurora/iconPerks_Hoarder',               lang = {'Power Struggle', '権力闘争', 'Wildes Herauswinden'} },   
}
